[package]
name = "cuview"
version = "0.1.0"
authors = ["Steven Dwy <yoplitein+git@gmail.com>"]
edition = "2018"

[lib]
name = "cuview"
path = "src/lib.rs"

[[bin]]
name = "cuview"
path = "src/main.rs"

[dependencies]
serde = "1.0.137"
serde_json = "1.0.81"

[dependencies.hematite-nbt]
version = "0.5.2"
features = ["serde"]
